### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by purepear** [Pajamaman/clean-html#1]
node_modules/clean-html/index.js:251:10

you can check if nodes are array.. sth like

```
function render(nodes) {
    var html = '';
    nodes = nodes || []

    nodes.forEach(function (node) {
...
```

**Comment by Pajamaman** [comment]
Sorry it took me so long to notice. Can you provide a sample that would cause this to happen?

**Comment by purepear** [comment]
I was doing some prototyping and i don't remember what the case was :) sorry

**Comment by purepear** [comment]
feel free to close it
