### ISSUE TITLE
working with patterns

### ISSUE THREAD

**Issue by smnbbrv** [Pajamaman/clean-html#10]
Hi,

the library is cool, I just need it to be a bit more functional. From what I understand currently it does not provide the ability to `remove-attributes` / `remove-tags` etc. by a pattern, so e.g. I want to remove all tags that match a pattern `/abc-[a-z0-9]+/i`.

Is it possible to have a feature like that?

**Comment by dave-kennedy** [comment]
That's a great idea. Can you submit a PR?

**Comment by smnbbrv** [comment]
please check #11

**Comment by dave-kennedy** [comment]
Featured merged. Thanks!
