### ISSUE TITLE
Generated HTML removed the <script> tag

### ISSUE THREAD

**Issue by faizalmy** [Pajamaman/clean-html#13]
![image](https://user-images.githubusercontent.com/1636216/31803922-f31fdda6-b588-11e7-9a8b-0c1b519affcf.png)

**Comment by faizalmy** [comment]
left is original, right is the generated one.

**Comment by dave-kennedy** [comment]
See #12. I'm willing to reevaluate the current (non) solution, but time is an issue. Do you want to take a stab at it?

**Comment by ryanblock** [comment]
I think a friendlier solution would be to have options (i.e. `remove-script`, `remove-style`, default to `true` so as not to break anyone) that would allow these tags to simply be ignored and left as-is.

Love clean-html's lightness (and cli interface!) but sadly stripping script and style makes it tough for us.

**Comment by dave-kennedy** [comment]
That's a good idea. I can add those when I have time or I'll accept a PR if you want to try.

**Comment by clockshark** [comment]
yeah I need that too!!!

**Comment by dave-kennedy** [comment]
Fixed in 6a1cc0d.
