### ISSUE TITLE
Is the clean-html npm package legit?

### ISSUE THREAD

**Issue by ryanblock** [Pajamaman/clean-html#14]
Hi Dave! 👋 

It looks like this project was [added to npm](https://www.npmjs.com/package/clean-html) by someone named [pajamaman](https://www.npmjs.com/~pajamaman) – is that you? Is that package legit?

Just trying to be security conscious and all that.

Thanks!

**Comment by ryanblock** [comment]
... nvm, just peeped [contributors](https://github.com/dave-kennedy/clean-html/graphs/contributors) and it looks like there too be pajamaman. Will close!

**Comment by dave-kennedy** [comment]
@ryanblock thanks for checking. Yes, that is me :)
