### ISSUE TITLE
How to remove all HTML 'attributes' or 'tags' EXCEPT a certain one (or two)

### ISSUE THREAD

**Issue by Nantris** [Pajamaman/clean-html#15]
I'd like to remove every attribute that isn't `src` or `href` but I'm having a hard time figuring out regex that I can pass to this option to achieve that. Is this currently possible?

Thanks again for the great package and for your help in the past.

**Comment by dave-kennedy** [comment]
Try `/^((?!src|href).)*$/`.

I don't quite understand it, but the explanation is [here](https://stackoverflow.com/a/406408/1015595).

**Comment by Nantris** [comment]
Thanks very much, I'll give this a shot!
