### ISSUE TITLE
img tag gets removed when using remove-empty-tags

### ISSUE THREAD

**Issue by appinteractive** [Pajamaman/clean-html#22]
When I use the `remove-empty-tags` option with any tag, `img` always gets removed.

```html
<p><img alt="" src="https://github.githubassets.com/images/modules/dashboard/copilot/bg.jpg"></p>
```

It's regardless of self closing or not, if I use even `picture` instead of `img`. They get always removed. Seems like a whitelist is processed under the hood!? 

Any idea @dave-kennedy ?

**Comment by appinteractive** [comment]
currently I come up with an ugly hack, I do transform the `img` tags to a `div` with some dummy content:

```js
const input = content.replace(
      /<img(.+?src=[\'"]([^\'"]+)[\'"].*?)>/g,
      "<div$1>IMAGE-HACK</div>", // hack to get images not removed
    );
```

and replace it back after cleanup

```js
.replace(
            /\<div(.+?src=[\'"]([^\'"]+)[\'"].*?)\>IMAGE-HACK\<\/div>/g, // hack to get images added back
            "<img$1 />",
          )
```

Its a temporary solution.

**Comment by dave-kennedy** [comment]
Sorry it took me so long to get back to you on this. This is definitely a bug. Thanks for reporting!
