### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by Nantris** [Pajamaman/clean-html#3]
Thanks for the excellent tool. I find when I paste more than 2 dozen or so lines, I get a maximum callstack exceeded error. Any thoughts of fixing this?

Thanks again!

**Comment by dave-kennedy** [comment]
Can you provide a sample so I can repro?

**Comment by dave-kennedy** [comment]
Actually, you might be running into a bug I fixed in 64ac394. Please pull down that version and see if it works for you.

**Comment by Nantris** [comment]
Hey Dave. Thanks very much for the update. I'll try out the new version and if I'm still hitting the issue I'll make an example repo when I can.

Thanks again for the great library! It's a great thing to have on hand. Must have saved me days and days of coding.

**Comment by Nantris** [comment]
Are you planning to release a versioned update I could pull via npm/yarn?

**Comment by dave-kennedy** [comment]
Yep, as soon as we can verify this bug is squashed. I was also hoping to address #4 and #5 in the next release, but I can publish sooner if it helps.

**Comment by dave-kennedy** [comment]
I published a new version (or three) to npm. Let me know if you're still having problems.

**Comment by Nantris** [comment]
Thanks a lot @dave-kennedy.

That will let me test it sooner. It will be a few days before I can give it a proper test.

**Comment by dave-kennedy** [comment]
Closed due to inactivity.

**Comment by Nantris** [comment]
Whoops thanks for updating the status of this. Yes the update did fix the issue. Sorry for not posting back. Great dev. I really appreciate the update you wrote to fix this issue.
